CELL_EMPTY = 0
CELL_HUMAN = 1
CELL_AGENT = 2

CELL_APPLE = 10
CELL_ORANGE = 20
CELL_APPLE_JUICE = 30
CELL_ORANGE_JUICE = 40

CELL_CUP = 100
CELL_JUICER = 200

CELL_TABLE = 1000
CELL_APPLE_STORAGE_OPEN = 2000
CELL_APPLE_STORAGE_CLOSE = 3000
CELL_APPLE_STORAGE_BUTTON = 4000
CELL_ORANGE_STORAGE_OPEN = 5000
CELL_ORANGE_STORAGE_CLOSE = 6000
CELL_ORANGE_STORAGE_BUTTON = 7000

ACTION_NULL = 0
ACTION_UP = 1
ACTION_DOWN = 2
ACTION_LEFT = 3
ACTION_RIGHT = 4
ACTION_TAKE = 5
ACTION_DROP = 6
ACTION_SQUEEZE = 7
ACTION_PRESS = 8

# position constants
PLAYGROUND_WIDTH = 8
PLAYGROUND_HEIGHT = 5
IMAGE_GROUND = "images/ground.png"
IMAGE_HUMAN = "images/human.png"
IMAGE_AGENT = "images/agent.png"
IMAGE_APPLE_STORAGE_CLOSED = "images/apple_closed_storage.png"
IMAGE_HUMAN_CARRY_APPLE = "images/human_carry_apple.png"
IMAGE_APPLE = "images/apple.png"
# initial position
PRINCIPAL_X = 0
PRINCIPAL_Y = 0
AGENT_X = 3
AGENT_Y = 4
STORAGE_X = 0
STORAGE_Y = 7
# key_order_type
ORDER_MOVE = ["w", "a", "s", "d"]
ORDER_TAKE = "j"
ORDER_DROP = "k"
