CELL_EMPTY = 0
CELL_HUMAN = 1
CELL_AGENT = 2

CELL_APPLE        = 10
CELL_ORANGE       = 20
CELL_APPLE_JUICE  = 30
CELL_ORANGE_JUICE = 40

CELL_CUP    = 100
CELL_JUICER = 200

CELL_TABLE = 1000
CELL_APPLE_STORAGE_OPEN    = 2000
CELL_APPLE_STORAGE_CLOSE   = 3000
CELL_APPLE_STORAGE_BUTTON  = 4000
CELL_ORANGE_STORAGE_OPEN   = 5000
CELL_ORANGE_STORAGE_CLOSE  = 6000
CELL_ORANGE_STORAGE_BUTTON = 7000

ACTION_NULL    = 0
ACTION_UP      = 1
ACTION_DOWN    = 2
ACTION_LEFT    = 3
ACTION_RIGHT   = 4
ACTION_TAKE    = 5
ACTION_DROP    = 6
ACTION_SQUEEZE = 7
ACTION_PRESS   = 8
